#!/usr/bin/env python3
"""Extract the C64 payload and player addresses from a PSID file."""

from __future__ import annotations

import sys
from pathlib import Path


def be16(data: bytes, offset: int) -> int:
    return int.from_bytes(data[offset : offset + 2], "big")


def write_if_changed(path: Path, contents: bytes) -> None:
    if path.exists() and path.read_bytes() == contents:
        return
    path.write_bytes(contents)


def fail(message: str) -> None:
    raise SystemExit(f"prepare_sid.py: {message}")


def main() -> None:
    if len(sys.argv) != 5:
        fail("usage: prepare_sid.py INPUT.sid OUTPUT.asm OUTPUT.bin OUTPUT-vice-args")

    source, config_path, payload_path, vice_args_path = map(Path, sys.argv[1:])
    data = source.read_bytes()
    if len(data) < 0x76 or data[:4] not in (b"PSID", b"RSID"):
        fail(f"{source} is not a valid PSID/RSID file")

    data_offset = be16(data, 6)
    load = be16(data, 8)
    init = be16(data, 10)
    play = be16(data, 12)
    songs = be16(data, 14)
    default_song = be16(data, 16)
    if data_offset >= len(data):
        fail(f"{source} has no C64 payload")
    if not 1 <= default_song <= songs:
        fail(f"{source} has an invalid default song number")

    payload = data[data_offset:]
    if load == 0:
        if len(payload) < 2:
            fail(f"{source} is missing the payload load address")
        load = int.from_bytes(payload[:2], "little")
        payload = payload[2:]
    if init == 0:
        init = load
    if play == 0:
        fail(f"{source} needs CIA-timer playback, which this 50 Hz player does not support")
    if load + len(payload) > 0x10000:
        fail(f"{source} payload exceeds C64 memory")
    if load < 0x1000 or load + len(payload) > 0x2800:
        fail(
            f"{source} payload (${load:04x}-${load + len(payload) - 1:04x}) "
            "does not fit the project's free SID area ($1000-$27ff)"
        )

    # PSID v2NG stores extra SID addresses as $D000 + (header byte * $10).
    # A zero byte means that the corresponding chip is not used.
    sid2 = data[0x7A] if len(data) >= 0x7C else 0
    sid3 = data[0x7B] if len(data) >= 0x7C else 0
    if sid3 and not sid2:
        fail(f"{source} declares a third SID without a second SID")
    extra_addresses = [0xD000 + value * 0x10 for value in (sid2, sid3) if value]
    vice_args = []
    if extra_addresses:
        vice_args.extend(("-sidextra", str(len(extra_addresses))))
        for index, address in enumerate(extra_addresses, start=2):
            vice_args.extend((f"-sid{index}address", f"0x{address:04x}"))

    config = (
        "; Generated by tools/prepare_sid.py; do not edit.\n"
        f"SID_LOAD = ${load:04x}\n"
        f"SID_INIT = ${init:04x}\n"
        f"SID_PLAY = ${play:04x}\n"
        f"SID_SONG = {default_song - 1}\n"
    ).encode()
    write_if_changed(config_path, config)
    write_if_changed(payload_path, payload)
    write_if_changed(vice_args_path, (" ".join(vice_args) + "\n").encode())


if __name__ == "__main__":
    main()
